#!/usr/bin/php -q 
<?php
class xcodeBuild  {

    public $workspace;
    
    public $scheme;

    public $appMacro;

    public $output;

    public $channel;

    public $certificate;

    public $version;

    public $infoPath;

    public $xcodeproj;

    // 原始bundleID
    private $originalBundleID;

    // 原始渠道
    private $originalChannelName;

    // 原始渠道
    private $originalApiServer;

    // project 是个xml 文件
    private $isXML;

    function __construct() {

        global $argv;

        if (!is_file($argv[1])) {
            exit("配置文件出错!\n");
        }

        $options = file_get_contents($argv[1]);
        $options = json_decode($options, true);

        if (!is_array($options)) {

            die("json配置文件解析失败");
        }

        $this->workspace = $options['workspace'];
        $this->scheme = $options['scheme'];
        $this->appMacro = $options['AppMacro'];
        $this->output = './output/';
        $this->channel = $options['channel'];
        $this->certificate = $options['certificate'];
        $this->version = intval($argv[2]);
        $this->infoPath = $options['infoPath'];
        $this->xcodeproj = $options['xcodeproj'];
    }

    public function exec($value) {
        passthru($value, $reset);
        if ($reset == 1) {
            // 替换回去
            $this->replaceData(1, $this->originalBundleID, $this->originalChannelName, $this->originalApiServer);
            die("编译失败.\n");
        }
        return $reset;
    }

    // 更新pod
    public function updateCocoapods() {
        
        $shell = "pod update --no-repo-update --verbose";
        $this->exec($shell);
        return $this;
    }

    public function clean() {

        $shell = "xcodebuild -workspace {$this->workspace} -scheme {$this->scheme} clean | xcpretty;";
        $this->exec($shell);
        return $this;
    }

    public function getOriginalInfo() {
        // 获取原始BundleID
        $shell = "cat {$this->xcodeproj}/project.pbxproj | grep -m1 'PRODUCT_BUNDLE_IDENTIFIER' | awk -F ' = ' '{print $2}' | awk -F ';' '{print $1}'";
        exec($shell, $shellReset);
        $this->originalBundleID = $shellReset[0];
        if (empty($this->originalBundleID)) {

            // 可能project.pbxproj变成了 XML 文件
            $file = file_get_contents("{$this->xcodeproj}/project.pbxproj");
            preg_match('/PRODUCT_BUNDLE_IDENTIFIER<\/key>(.*?)<string>(.*?)<\/string>/s', $file, $shellReset);
            $this->originalBundleID = $shellReset[2];
            if (empty($this->originalBundleID)) {
                die("BundleID 获取失败");
            }
            $this->isXML = true;
        }
        unset($shellReset);

        // 获取原始渠道 ID
        $shell = "cat {$this->appMacro} | grep -m1 'kchannelId'| awk -F '\"' '{print $2}'";
        exec($shell, $shellReset);
        
        $this->originalChannelName = $shellReset[0];
        if (empty($this->originalChannelName)) {
            die("原始渠道获取失败");
        }
        unset($shellReset);

        $shell = "cat {$this->appMacro} | grep -m1 'kAPI_USER_SERVER'| awk -F '\"' '{print $2}'";
        exec($shell, $shellReset);
        $this->originalApiServer = $shellReset[0];

        if (empty($this->originalApiServer)) {
            die("原始ApiServer获取失败");
        }

        unset($shellReset);

        return $this;
    }

    public function bulid() {

        // 当前版本号
        $shell = "/usr/libexec/PlistBuddy -c \"print CFBundleShortVersionString\" {$this->infoPath};";
        $this->exec($shell);
        
        // 获取原始资源
        $this->getOriginalInfo();

        // 删除文件夹
        if (!empty($this->output) && is_readable($this->output)) {

            $this->exec('rm -fr '.$this->output);
        }

        foreach ($this->channel as $channel) {
           
            $codesign = $this->certificate[$channel['channelType']]['codesign'];
            $certificate = $this->certificate[$channel['channelType']]['profile'];

            if ($channel['channelType'] == 'AppStore') {

                $shell = 'sed -i "" "s/#define IS_FORMAL.*/#define IS_FORMAL 1/g" '.$this->appMacro;
                $this->exec($shell);
            } else {

                $shell = 'sed -i "" "s/#define IS_FORMAL.*/#define IS_FORMAL 0/g" '.$this->appMacro;
                $this->exec($shell);
            }

            $this->replaceData($this->version, $this->certificate[$channel['channelType']]['buildID'], $channel['channnelName'], $channel['apiServer']);

            $output = $this->output."/{$this->version}/{$channel['channnelName']}/{$channel['channnelName']}";
            $shell = "xcodebuild -workspace {$this->workspace} -scheme {$this->scheme} -destination generic/platform=iOS archive -archivePath {$output}.xcarchive CODE_SIGN_IDENTITY=\"{$certificate}\" PROVISIONING_PROFILE=\"{$codesign}\" | xcpretty;";
            
            $this->exec($shell);

            // 打包
            $shell = 'xcodebuild -exportArchive -archivePath '.$output.'.xcarchive -exportPath '.$output.'  -exportFormat ipa -exportProvisioningProfile '.$this->certificate[$channel['channelType']]['ProvisioningProfile'].' | xcpretty;';
            
            $this->exec($shell);

            // 测试包
            $this->exec('ipa info '.$output.'.ipa');

            // 保存dsym
            $this->exec('mv '.$output.'.xcarchive/dSYMs/* '.$this->output."/{$this->version}/{$channel['channnelName']}/");
            $this->exec('mv '.$output.'.xcarchive/Info.plist '.$this->output."/{$this->version}/{$channel['channnelName']}/");
            $this->exec('rm -fr '.$output.".xcarchive");

            $shell = '/usr/libexec/PlistBuddy -c "Set :CFBundleVersion 1" '.$this->infoPath;
            $this->exec($shell);

            // 替换回去
            $this->replaceData(1, $this->originalBundleID, $this->originalChannelName, $this->originalApiServer);
        }
        
        return $this;
    }

    // 替换资源
    public function replaceData($version, $bundle_id, $channnelName, $apiServer) {

        $apiServer = str_replace('/', '\\\\/', $apiServer);
       
        // 更改CFBundleVersion
        $shell = '/usr/libexec/PlistBuddy -c "Set :CFBundleVersion '.$version.'" '.$this->infoPath;
        $this->exec($shell);
        
        // 替换 buildid
        if ($this->isXML) {

            $file = file_get_contents("{$this->xcodeproj}/project.pbxproj");
            $project_content = preg_replace('/PRODUCT_BUNDLE_IDENTIFIER<\/key>(.*?)<string>(.*?)<\/string>/s', 'PRODUCT_BUNDLE_IDENTIFIER</key>${1}<string>'.$bundle_id.'</string>', $file);
            file_put_contents($this->xcodeproj.'/project.pbxproj', $project_content);

        } else {

           $shell = 'sed -i "" "s/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = \"'.$bundle_id.'\";/g" '.$this->xcodeproj.'/project.pbxproj';
            $this->exec($shell); 
        }
        

        // 替换渠道
        $shell = 'sed -i "" "s/kchannelId.*/kchannelId @\"'.$channnelName.'\"/g" '.$this->appMacro;
        $this->exec($shell);

        // 替换服务器地址
        $shell = 'sed -i "" "s/kAPI_USER_SERVER.*/kAPI_USER_SERVER @\"'.$apiServer.'\"/g" '.$this->appMacro;
        $this->exec($shell);
    }
}

$bulid = new xcodeBuild();
$bulid->updateCocoapods()->clean()->bulid();

